### ISSUE TITLE
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by josegamboa** [apache/cordova-cli#589] opened 2022-11-05 23:45 UTC
Hi guys,

I have tried to install Cordova on Mac OS 13 and it seems like there is  problem with lates versions, tried to install cordova 10 and 11 and I got same error.

# Bug Report
 Mac OS 13 Ventura

## Problem
I have installed Cordova 10.0.0 NodeJs 14 and it seems like there is an issue

` npm install -g  cordova@10.0.0  `
`cordova - version`

### What is expected to happen?
To return Cordova version 

### What does actually happen?
Returning an exception

## Information
`TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at macosRelease (/usr/local/lib/node_modules/cordova/node_modules/macos-release/index.js:28:26)
    at osName (/usr/local/lib/node_modules/cordova/node_modules/os-name/index.js:21:18)
    at new Insight (/usr/local/lib/node_modules/cordova/node_modules/insight/lib/index.js:37:13)
    at new RelentlessInsight (/usr/local/lib/node_modules/cordova/src/telemetry.js:31:1)
    at Object.<anonymous> (/usr/local/lib/node_modules/cordova/src/telemetry.js:39:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)`

### Command or Code
`cordova - version`

### Environment, Platform, Device
Mac OS 13 - Ventura

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by rajohns08** [comment] 2023-01-25 02:22
Copying my comment from https://github.com/apache/cordova-cli/issues/566:

Yeah looks like the insight package is basically throwing in the towel on this issue, and the creator removed it from his own product: https://github.com/yeoman/insight/issues/83. So that is likely the best path forward for cordova as well.

**Comment by breautek** [comment] 2023-05-17 18:12
Closing this as not a bug.

The issue is resolved in insight@0.11, which will only be used in cordova@11 and later.

This is because insight@0.11 will use os-name@4 which now surrounds the problematic code in a try/catch to avoid a hard crash. It does mean that telemetry won't receive human friendly names, but that's not a concern for cordova users.

So upgrade to cordova@11 or later.

**Closed by breautek** 2023-05-17 18:12 UTC
Labels: bug
