### ISSUE TITLE
ionic cordova prepare

### ISSUE THREAD

**Issue by jhonnathanH** [apache/cordova-cli#527] opened 2020-08-24 01:43 UTC
# Bug Report

## Problem
Unable to load Platform API from C:\...\..\..\platforms\android\cordova\Api.js:
Cannot find module 'C:\...\..\..\platforms\android\cordova\Api.js'   
### What is expected to happen?

i cant build anymore

## Information
only try to deploy with ionic 5 and cordova and fail

### Command or Code
ionic cordova prepare android

### Version information
Ionic:

   Ionic CLI                     : 5.4.16 (C:\Users\alcon\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.901.11
   @angular-devkit/schematics    : 9.1.11
   @angular/cli                  : 9.1.11
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 2.2.1
   @capacitor/core : 2.2.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : none
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 18 other plugins)

Utility:

   cordova-res (update available: 0.15.1) : 0.12.1
   native-run (update available: 1.0.0)   : 0.2.8

System:

   Android SDK Tools : 26.1.1 (C:\Users\alcon\AppData\Local\Android\Sdk)
   NodeJS            : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10

## Checklist

- [ ] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by brodybits** [comment] 2020-08-24 12:03
Ionic is a third-party toolset not supported by Apache Cordova. Thanks.

**Comment by pseudooriginal** [comment] 2020-08-26 07:51
Same problem with `cordova platform add android`, the package cordova-android isn't added in the package.json after the command.

**Comment by brodybits** [comment] 2020-08-26 12:45
I suspect something is wrong in your environment. I recommend that you double-check that you have most recent Cordova CLI (10) and try again with a new project. In case of issues with a new project, it would be best to walk us through a reproduction in a new issue with all info requested by the issue template.

**Comment by breautek** [comment] 2020-08-29 00:27
You can try the following commands (if you're on linux/mac bash environment, sorry not sure on the windows equivalent commands)

```
cd to/your/cordova/project/folder
rm -rf node_modules
rm package-lock.json
npm install
cordova platform add android
```

**Comment by jayenashar** [comment] 2021-01-14 03:23
how do i recover if something is messed up in my environment?  this project was working when i last used it (maybe one year ago), but didn't work today.  i tried upgrading all cordova packages, and i've tried what @breautek suggested and now have:

```
jayen@eeyore:~/cordova$ npx cordova platform add android --save
Using cordova-fetch for cordova-android@9.0.0
Platform android already added.
jayen@eeyore:~/cordova$ npx cordova prepareUnable to load Platform API from /home/jayen/cordova/platforms/android/cordova/Api.js:
Cannot find module '/home/jayen/cordova/platforms/android/cordova/Api.js'
Require stack:
- /home/jayen/cordova/node_modules/cordova-lib/src/cordova/util.js
- /home/jayen/cordova/node_modules/cordova-lib/src/platforms/index.js
- /home/jayen/cordova/node_modules/cordova-lib/src/platforms/platforms.js
- /home/jayen/cordova/node_modules/cordova-lib/src/plugman/install.js
- /home/jayen/cordova/node_modules/cordova-lib/src/plugman/plugman.js
- /home/jayen/cordova/node_modules/cordova-lib/cordova-lib.js
- /home/jayen/cordova/node_modules/cordova/src/help.js
- /home/jayen/cordova/node_modules/cordova/src/cli.js
- /home/jayen/cordova/node_modules/cordova/bin/cordova
1 jayen@eeyore:~/cordova$ npx cordova --version
10.0.0
```

**Comment by breautek** [comment] 2021-01-28 03:19
Closing due to staleness.

**Closed by breautek** 2021-01-28 03:19 UTC
Labels: info-needed
