### ISSUE TITLE
Cordova cli is installing a very old plugin

### ISSUE THREAD

**Issue by realtebo** [apache/cordova-cli#598] opened 2022-12-29 09:41 UTC
I don't know if this is a bug or not. So I cannot open a bug. 

I am adding to a fresh new project the cordova-plugin-file using cordova cli.

cordova is at v11.0.0. 

When adding the plugin, it adds me the version 7, while the plugin itself is now at v 11. 

```
"devDependencies": {
    "cordova-android": "^10.1.2",
    "cordova-plugin-file": "^7.0.0"
  },
```

Why?

```
cordova info

Cordova Packages:

    cli: 11.0.0
        common: 4.1.0
        create: 4.0.0
        lib: 11.0.0
            common: 4.1.0
            fetch: 3.1.0
            serve: 4.0.0

Project Installed Platforms:

    android: 10.1.2

Project Installed Plugins:

    cordova-plugin-file: 7.0.0

Environment:

    OS: Microsoft Windows 11 Pro 10.0.22621 (22621) (Windows 10.0.22621) x64
    Node: v14.19.1
    npm: 6.14.16

android Environment:

    android:
ERROR: Command failed with exit code 1: avdmanager list target
"avdmanager" non � riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.


Project Setting Files:

    config.xml:
<?xml version='1.0' encoding='utf-8'?>
<widget id="it.realtebo.offline" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>it.realtebo.offline</name>
    <description>Test Offline Download e DB</description>
    <author email="dev@cordova.apache.org" href="https://cordova.apache.org">
        Apache Cordova Team
    <allow-intent href="https://*/*" />
    <allow-navigation href="about:*" />
</widget>

    package.json:
--- Start of Cordova JSON Snippet ---
{
  "platforms": [
    "android"
  ],
  "plugins": {
    "cordova-plugin-file": {
      "ANDROIDX_WEBKIT_VERSION": "1.4.0"
    }
  }
}
--- End of Cordova JSON Snippet ---
```

**Comment by NiklasMerz** [comment] 2022-12-29 09:48
The latest version of the file plugin is 7.0.0 https://www.npmjs.com/package/cordova-plugin-file

**Comment by erisu** [comment] 2022-12-29 09:49
Closing as not a bug and not an issue.

Cordova CLI 11.0.0 has nothing to do with the version of the file plugin.
The current major release of the Cordova file plugin is version 7. https://www.npmjs.com/package/cordova-plugin-file

**Closed by NiklasMerz** 2022-12-29 09:48 UTC

**Comment by realtebo** [comment] 2022-12-29 09:51
Why is version 7?

See here: https://cordova.apache.org/docs/en/11.x/reference/cordova-plugin-file/ 

Latest version is 11.0 

Should I ask to some other repo why new versions are not published?

**Comment by erisu** [comment] 2022-12-29 09:57
That is the doc version, which is based off of the Cordova CLI. When a new major version of CLI is released, the docs get a new release as well.
