### ISSUE TITLE
Package.json is being modified after cordova build android

### ISSUE THREAD

**Issue by distante** [apache/cordova-cli#394] opened 2019-01-02 20:33 UTC
**Description:**
I work in a windows environment with vscode where all files need to end with `CRLF `, so this configs are made:

* `.editorconfig` the `end_of_line` property is set to `crlf`
* `git` uses crlf
* `.prettierrc` has  `"endOfLine": "crlf"`
* vscode config has `"files.eol": "\r\n"` and `"prettier.endOfLine": "crlf"`

All work as expected except for when you build (or run) the project on device. `> cordova build android` the `package.json` file is edited and stripped from the last empty line. That leads git say changes where made and the tree is not clean.

**Steps to Reproduce:**
* Make a clean cordova project (or if you use Ionic as I do, then an ionic empty project)
* Set eol to crlf
* Add platform Android
* Make sure `package.json` has a empty new line in the end.
* Run `cordova build android`

**Output:**
![image](https://user-images.githubusercontent.com/5490201/50472339-b2ce2e80-09b8-11e9-885d-4ba4300f629a.png)

I had this problem with cordova version 8.0.0 and right now with 8.1.2

Edit: As per [this comment](https://github.com/apache/cordova-cli/issues/394#issuecomment-456490422), this problem also happens in iOS

**Comment by jwhitmarsh** [comment] 2019-01-22 17:35
Affecting iOS too

**Comment by doug-a-brunner** [comment] 2019-04-04 23:58
Still exists on CLI 9.0.0.

**Comment by dpogue** [comment] 2019-04-05 00:16
Yep, this won't be fixed until we do a complete refactor of our package.json handling. The first part of that work is https://github.com/apache/cordova-common/pull/34 which needs a lot more work before it's ready to merge

**Comment by raphinesse** [comment] 2019-04-11 21:17
AFAICT, this is a duplicate of https://github.com/apache/cordova-cli/issues/353. Someone please yell at me if that's not right. Closing for now.

**Closed by raphinesse** 2019-04-11 21:17 UTC
Labels: duplicate, platform: android, support

**Comment by arzyu** [comment] 2019-09-10 08:25
I created a plugin to solve this issue. 

https://github.com/arzyu/cordova-plugin-package-json-guard

**Comment by u01jmg3** [comment] 2020-06-10 11:45
Plugin from @arzyu did the trick

**Comment by Dealerpriest** [comment] 2020-11-18 13:25
> I created a plugin to solve this issue.
> 
> https://github.com/arzyu/cordova-plugin-package-json-guard

How about config.xml? Do the plugin handle that aswell?
