### ISSUE TITLE
`cordova plugin add ..`: "ELOOP: too many symbolic links encountered"

### ISSUE THREAD

**Issue by janpio** [apache/cordova-cli#438] opened 2019-05-27 18:06 UTC
I tried to create a `testApp` in a checkout of a plugin, and then add the plugin with `cordova plugin add ..`. This caused the following output:

```
E:\Projects\Cordova\cordova-plugin-whitelist (janpio-tests -> origin) (cordova-plugin-whitelist@1.3.4-dev)
λ cordova create testApp
Creating a new cordova project.

E:\Projects\Cordova\cordova-plugin-whitelist (janpio-tests -> origin) (cordova-plugin-whitelist@1.3.4-dev)
λ cd testApp

E:\Projects\Cordova\cordova-plugin-whitelist\testApp (janpio-tests -> origin) (helloworld@1.0.0)
λ cordova plugin add ..
ELOOP: too many symbolic links encountered, stat 'E:\Projects\Cordova\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist\testApp\node_modules\cordova-plugin-whitelist'
```

---

Background: Would be handy if one could create a test app for a plugin via an npm script inside the plugin folder (e.g. `cordova create testApp && cd testApp && cordova plugin add .. && cordova plugin add ../test && cordova plugin add cordova-plugin-test-framework && cordova platform add anroid && cordova run android`), but that would required this command to not fail.

**Comment by raphinesse** [comment] 2019-05-27 18:23
Duplicate of #401

You even commented on that. Ts ts ts :wink:

**Closed by raphinesse** 2019-05-27 18:23 UTC

**Comment by janpio** [comment] 2019-05-27 20:36
Well, at least one of us has a memory.
