### ISSUE TITLE
Fixed/Freezed versions for plugins

### ISSUE THREAD

**Issue by caipivara** [apache/cordova-cli#396] opened 2019-01-09 19:22 UTC
Using cli version `7.1.0`:

I want to use the version `8.0.3` for some library but when I use:

```
cordova plugin add instabug-cordova@8.0.3 --save
```

The `config.xml` ends up with: `instabug-cordova@^8.0.3` meaning that minor changes should be installed too, and at the end the version that the project try to use is `8.0.4` and not `8.0.3`. 

- Is there any way to define fixed versioning on a dependency? 
- Why this always allow minor changes on versioning? this does not ends up with a dependency bug hell?

**Comment by brodybits** [comment] 2019-01-09 23:42
Cordova CLI `8.1.2` seems to add the exact version to config.xml and package.json, if you specify the exact version of the plugin. (I tried it with the exact command you gave.) Please consider upgrading since we do not support old Cordova package versions.

It is possible to use newer Cordova CLI version with older platform versions, if necessary for any reason. I would also recommend you guys consider upgrading to the latest version of Cordova platforms since we do not support older platform packages.

**Comment by dpogue** [comment] 2019-01-09 23:45
I believe you can run `--save-exact` to save the exact version rather than the semver-compatible version.

We save a semver-compatible (`^`) version for consistency with npm.

**Comment by raphinesse** [comment] 2019-04-11 20:03
Closing since not reproducible in Cordova CLI 8.1.2 according to @brodybits. Cordova 7 has definitely hit EOL.

**Closed by raphinesse** 2019-04-11 20:04 UTC
Labels: invalid, support
