### ISSUE TITLE
cordova@8.1.0 error prompt is not a function on MacOS

### ISSUE THREAD

**Issue by wyne1986** [apache/cordova-cli#341] opened 2018-09-27 07:44 UTC
cordova@8.1.0 error prompt is not a function on MacOS

**Comment by raphinesse** [comment] 2018-09-27 07:46
Duplicate of #337. Thanks for reporting, we're working on it. In the meanwhile roll back to 8.0 please.

**Closed by raphinesse** 2018-09-27 07:46 UTC
Labels: duplicate
