### ISSUE TITLE
cordova plugin remove command still gives variable missing for variables already specified

### ISSUE THREAD

**Issue by premedios-i9** [apache/cordova-cli#578] opened 2022-04-11 11:32 UTC
# Bug Report

## Problem
```cordova plugin rm``` gives ```variables missing``` error for variables already specified in command.

### What is expected to happen?
It should not give the error because I have specified all required variables.

### What does actually happen?
It gives a ```variables missing``` error for variables that are already specified in the command line.

### Command or Code
```cordova plugin rm cordova-plugin-teladoc --variable CALENDARS_USAGE_DESCRIPTION="description" --variable CAMERA_USAGE_DESCRIPTION="description" --variable LOCATION_ALWAYS_AND_WHEN_IN_USE_DESCRIPTION="description" --variable LOCATION_ALWAYS_USAGE_DESCRIPTION="description" --variable LOCATION_WHEN_IN_USE_DESCRIPTION="description" --variable MICROPHONE_USAGE_DESCRIPTION="description" --variable PHOTO_LIBRARY_USAGE_DESCRIPTION="description"```

### Environment, Platform, Device
macOS 12.3.1 Monterey

### Version information

Cordova 11, cordova-ios 6.2.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment] 2022-04-11 12:27
I will be closing out this issue because it is a duplicate of https://github.com/apache/cordova-cli/issues/446.

**Closed by erisu** 2022-04-11 12:28 UTC

**Comment by erisu** [comment] 2022-04-11 12:38
Can you provide steps to reproduce this issue?

It appears the plugin is not in the npm registry and can not be installed.

If you can provide the same issue with a publicly available plugin, that will help us better trace the bug.
